version: '3.5'

services:
  postgres:
    image: postgres:15.4-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456

  redis:
    image: redis:7.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  postgres:
  redis: